image: node

pipelines:
  pull-requests:
    '**':
      - step:
          caches:
            - npm
          name: Validate schemas
          script:
            - make check
  tags:
    '*':
      - step:
          artifacts:
            - schema-*.yaml
          caches:
            - npm
          name: Combine schemas
          script:
            - make
      - step:
          name: Upload to Bitbucket Downloads
          script:
            - make upload
      - step:
          artifacts:
            - doc/**
          caches:
            - npm
          name: Generate documentation
          script:
            - make doc

definitions:
  caches:
    npm: $HOME/.npm

