image: node

pipelines:
  pull-requests:
    '**':
      - step:
          caches:
            - npm
          name: Validate schemas
          script:
            - make check
  tags:
    '*':
      - step:
          artifacts:
            - schema-*.yaml
          caches:
            - npm
          name: Combine schemas
          script:
            - make

definitions:
  caches:
    npm: $HOME/.npm

